version: "3"

services:
    influxdb:
        container_name: influxdb
        image: influxdb:1.7.4-alpine
        volumes:
            - ./influxdb/etc:/etc/influxdb
            - influxdb_lib:/var/lib/influxdb
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
        ports:
            - 8083:8083
            - 8086:8086

    grafana:
        container_name: grafana
        image: grafana/grafana:5.4.3
        volumes:
            - ./grafana/etc:/etc/grafana:ro
            - grafana_lib:/var/lib/grafana
            - grafana_log:/var/log/grafana
        links:
            - influxdb:influxdb
        environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel
        ports:
            - 3000:3000
        depends_on:
            - influxdb

volumes:
  influxdb_lib:
    external: false

  grafana_lib:
    external: false

  grafana_log:
    external: false
